### ISSUE TITLE
Commiting Problem

### ISSUE THREAD

**Issue by Gu-Youngfeng** [VicLily/test#186]
I don't know what have you finished in these <b>518</b> commits! Each file only contains a <b>few</b> lines (1-2 Loc),  additionally, I don't know how to use this project(<b>No introduction</b> in README.md). So can author come out and teach me what's the MOTIVATION of this test project :)

Did you usually <del>delete</del> some words in the files and then <code>add</code> some words to increase the commits number?

**Comment by VicLily** [comment]
:smile:

**Comment by Gu-Youngfeng** [comment]
It's so bad, **CLOSE** the issue without solving my problem!
---
So bad~ . I'm not happy :(
